name: DenaZavier
favicon: null
layout_spectrum: 0.2654080712236464
typography_spectrum: 0.7914940423797816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9460487875621766
  lightness: 0.29954510228708386
  saturation: 0.5760191248264164
  rhythmicContrast: 0.40512661752291024
purpose: []
